let money = 2000;
let income = 'freelance';
let addExpenses = 'Internet, taxi, communal flat';
let deposit = true;;
let mission = 20000;
let period = 12;
console.log( typeof(money), typeof(income), typeof(deposit) );
console.log(addExpenses.length);
console.log('Период равен ' + period + ' месяцев');
console.log('Цель заработать ' + mission + ' долларов');
console.log(addExpenses.toLowerCase());
console.log(addExpenses.split(', '));
let budgetDay = money/30;
console.log(budgetDay);